apiVersion: v1
kind: Service
metadata:
  name: mailgate-server
  namespace: mailgate
  labels:
    app: mailgate-server
    app.kubernetes.io/name: mailgate-server
spec:
  selector:
    app: mailgate-server
  ports:
    - name: http
      port: 31101
      targetPort: http
    - name: grpc
      port: 31102
      targetPort: grpc
    - name: debug
      port: 31103
      targetPort: debug
