apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailgate-data
  namespace: mailgate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
